app:
  build: .
  command: "yarn start"
  ports:
    - 3000:3000

selenium:
  image: 'selenium/standalone-chrome:3.11.0-californium'
  expose:
    - "4444"
  links:
    - app
  log_driver: "none"

test:
  build: .
  command: "yarn test --host selenium"
  links:
    - selenium

